# -*- coding: utf-8 -*-
"""Tugas1-Nomor3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1liEBt4Xwb_zf881-iAjIo0MQDXQXofdC
"""

#3. Buatlah sebuah variabel dengan tipe data array, kemudian tampilkan semua nilai dalam variabel tersebut menggunakan perulangan for
# Daftar penyanyi favorit
penyanyi_favorit = ["Adele", "Ed Sheeran", "Taylor Swift", "Beyonce", "Bruno Mars"]

# Menentukan aksi berdasarkan penyanyi favorit
for penyanyi in penyanyi_favorit:
    if penyanyi == "0":
        aksi = "menyanyikan lagu-lagu penuh emosi."
    elif penyanyi == "1":
        aksi = "menulis dan menyanyikan lagu-lagu romantis."
    elif penyanyi == "2":
        aksi = "menciptakan lagu-lagu dengan cerita kehidupan."
    elif penyanyi == "3":
        aksi = "mempesona panggung dengan penampilan spektakuler."
    elif penyanyi == "4":
        aksi = "menyajikan kombinasi musik funk, pop, dan R&B yang energetik."
    else:
        aksi = "membuat karya musik yang unik dan menginspirasi."

    print(f"{penyanyi} dikenal karena {aksi}")