# -*- coding: utf-8 -*-
"""Tugas1-Nomor2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VE6MWVIFerlQ2drEEeuCVGTHuoCE6-6K
"""

#2. Buatlah program bebas, dengan menerapkan if else pada:
  #a. For Loops
# Rentang suhu dalam derajat Celsius
batas_bawah = 18
batas_atas = 32

for suhu in range(batas_bawah, batas_atas + 1):
    if suhu >= 30:
        status = "panas"
    elif 20 <= suhu < 30:
        status = "nyaman"
    else:
        status = "dingin"

    print(f"Suhu {suhu} derajat Celsius diklasifikasikan sebagai suhu {status}.")

#b. While Loops

# Inisialisasi suhu awal
suhu = 18

# Batas atas suhu
batas_atas = 32

while suhu <= batas_atas:
    if suhu >= 30:
        status = "panas"
    elif 20 <= suhu < 30:
        status = "nyaman"
    else:
        status = "dingin"

    print(f"Suhu {suhu} derajat Celsius diklasifikasikan sebagai suhu {status}.")

    # Increment suhu untuk menghindari perulangan tanpa batas
    suhu += 1