# -*- coding: utf-8 -*-
"""Tugas1-Nomor1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1By4rG3fss5X1hefrTGfyljh03i3m4y8m
"""

#1. Buatlah perulangan hingga 100 menggunakan Python dengan output sebagai berikut:
# (https://github.com/randiijulian/randiijulian/assets/81604461/e32b6d92-7e3a-4323-a0e3-711009112c8e)
nama = "Muhammad Salman Alfarizi"

for angka in range(1, 101):
    if angka % 10 == 0:
      for kelipatan10 in range(3):
            print(nama)
    else:
        print(angka)